parameters:

services:
  CoreSys\UserManagement\Manager\SecurityManager:
    autowire: true
    class: CoreSys\UserManagement\Manager\SecurityManager
    arguments: 
      - '@Symfony\Component\HttpKernel\KernelInterface'
      - '@Symfony\Component\Form\FormFactoryInterface'
      - '@CoreSys\UserManagement\Repository\RoleRepository'
      - '@CoreSys\UserManagement\Repository\AccessRepository'
